name: Simple CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run tests
        run: python tests.py

      - name: Generate result
        run: python main.py

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculation-result
          path: result.txt
